### ISSUE TITLE
Onboarding Volunteers

### ISSUE THREAD

**Issue by TheSahithi** [cbitosc/djangocamp-hyd#10]
- [x] Volunteers list

Details to be collected

- [x] Expertise in Django & Python 

- [x] Contribution Type(Design, code, planning etc)

- [x] Number of Hours they can contribute

- [x] Others

**Comment by TheSahithi** [comment]
Should list out the perks of being a Volunteer and the basic instructions/ guidelines of being a volunteer.

**Comment by vihar** [comment]
List Of Volunteers
Eswar
Soumith Peketi
Akhil S
Himanshu K
Dileep
Preethi
Akhil
Harsha
Suraj
Tejaswi
Rohit
Chandu
Vishnu
Revanth
Jaahnavi
Akhil
Samhita
Ajay
Shreya
Ujwal
Mrudula
Madhurima
Akbar
Gopal
Aaqil
Krishnaveni
Harshitha

**Comment by vihar** [comment]
OC JOB DESCRIPTIONS

COMPTROLLING:
1. Gopal
2. Harshitha Patel

PUBLICITY:

1. Krishnaveni
2. Sri Akhil K
3. Vishnu Rohit
4. Suraj bodapati
5. Revanth R
6. Divyanshu
7. Aashish
8. Soumith Peketi
9. Preethi 

EDITORIAL:

1. Shreya Raj
2. U.Mrudula


DEVELOPERS:

1. Chandrahas Reddy Mandapati
2. Kannuri Ajay
3. Samhita Alla
4. Aaquil Shaik
5. KT Ujwal 

DESIGN :
1. V.Alekhya Rao
2. Akbar

PHOTOGRAPHY :
1. Jaahnavi Goli
2. Kolipaka sagar
3. Akhil
4. Eswar

RESOURCE MANAGEMENT:

1. Sadhvika Brahmani Thota
2. Nayakam Shivani

SESSION MANAGEMENT:
1. Veeram Reddy Sai Tejaswie
2. Madhurima

FOOD AND BEVERAGES :

1. Akhil Somalanka
2. Rohit Sai
3. Kiran Kumar
