### ISSUE TITLE
Workshop Requirements

### ISSUE THREAD

**Issue by TheSahithi** [cbitosc/djangocamp-hyd#4]
Lab setup
 - [x] Mic
 - [x] Projector
 - [x] Speakers
- [ ] Internet
- [ ] DJango software installed
- [ ] Python 3 installed

**Comment by sainithin95** [comment]
- [ ] Halls for Min 200 Students

**Comment by TheSahithi** [comment]
Are we planning for 200 attendees for workshop @sainithin95 ????

**Comment by vihar** [comment]
All the software will be installed today, and the expected people are 120 Members.
Mic, Speakers will be arranged today.
Issue Pending.
