### ISSUE TITLE
Design & Printing

### ISSUE THREAD

**Issue by sainithin95** [cbitosc/djangocamp-hyd#6]
- [x] Poster ( Online media and Offline campign  )

- [ ] Frame for Facebook Profile Pic

- [x] Design for T - Shirt 

- [ ] Banners

- [ ] Certificates

**Comment by vihar** [comment]
Banner and Poster designs printing will be done by today evening.

**Comment by sainithin95** [comment]
what about certificates digital printed ( Name ) or hand written  ?

**Comment by vihar** [comment]
Hand Written.

**Comment by sainithin95** [comment]
Do we have any Theme for that ?
