### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by TheSahithi** [cbitosc/djangocamp-hyd#8]
- [ ] Menu

- [ ] Food  arrangements (Veg) for Workshop attendees

- [ ]  Food  arrangements (Veg & Non-Veg) for Camp attendees

**Comment by ranjithrajv** [comment]
Who are the assignees of this task?

**Comment by vihar** [comment]
Food we gave the letter to canteen people, we will order based on the number of people attend.

**Comment by ranjithrajv** [comment]
I don't see any assignees for this issue from organizing team.
