### ISSUE TITLE
Volunteer Recruitments

### ISSUE THREAD

**Issue by sairamraavi** [cbitosc/djangocamp-hyd#9]
1.Eligibility criteria for volunteers
- Basics of Python
- Before the camp all the Volunteers should have done at-least a web application using Django
- All Volunteers should attend all the Run-up events 

2. Benifits as volunteers 
- [x] Internships
- [ ] Special goodies
- [x] Seperate certificate for the Volunteers

**Comment by TheSahithi** [comment]
The eligibility criteria doesn't seem to be apt for the people who would be coming for Volunteering @sairamraavi . Most of them may be freshers.
